### ISSUE TITLE
Custom acl.xml

### ISSUE THREAD

**Issue by umithyo** [4O4/mtasa-docker#2]
First off, thanks for the docker image. It is brilliant and runs seamlessly!

I was wondering if you could set customized acl.xml just the way you do with mtaserver.conf. I'd like to keep my acl.xml files in my repo without having to link the volume if we can handle it with your environmental variable magic.

**Comment by 4O4** [comment]
Thanks, I'm glad you find it useful! ACL.xml along with other configs and databases are in the `/data` directory inside the container. You have to mount this volume to some directory on your host OS (preferably with `-v $(pwd)/data:/data` switch) and that's all. 

If you want to store the whole data directory or just a few files from there in your repository - that's absolutely fine, you can safely do so. No magic variables are really necessary here unless I'm missing something :)

**Comment by umithyo** [comment]
I am currently using it like that yeah. I just wondered if it'd be more convenient to use multiple acl.xml files. Like, I use user.* for local and user.ThisUserIsDevOnly. But if you want it to stay like this, then sure. Thanks for the reply!

**Comment by 4O4** [comment]
> I am currently using it like that yeah. I just wondered if it'd be more convenient to use multiple acl.xml files. Like, I use user.* for local and user.ThisUserIsDevOnly. 

That might actually be a good idea, I'll think about and will let you know.
