### ISSUE TITLE
Beta MTA Versions

### ISSUE THREAD

**Issue by umithyo** [4O4/mtasa-docker#3]
Is it possible to build beta versions of MTA:SA? I kind of rely on a feature that's been on hold for too long (kicking peds out of the vehicle) which requires using the beta version. Is that too much of a hassle?

**Comment by 4O4** [comment]
Sure, I can automatically build image with any version of MTA, it's not a big deal at all. Last month we've pushed tag 1.5.8-20833-v1 which (as the name suggests) contains nightly build 20833. If that's high enough version for you you can pull it right now from dockerhub. If you need a newer build, just give me the specific build number. Please be aware that not all nightly builds are fully stable, they may contain some bugs, so it's always good to check commit messages at https://buildinfo.mtasa.com to get some idea what to expect from given build number :)

**Comment by umithyo** [comment]
I guess I was not paying attention to tags. 1.5.8-20833-v1 is good enough for me. Thanks a lot!
